apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: demoapp
  namespace: production
spec:
  containers:
  - name: nginxseverdemo
    image: nginx
    ports:
    - containerPort: 80
